"""empty message

Revision ID: 13934f10a019
Revises: 
Create Date: 2019-10-04 16:58:16.891916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13934f10a019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('street_number', sa.String(length=255), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('apt_number', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('administrative_area_level_1', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=40), nullable=True),
    sa.Column('current_login_ip', sa.String(length=40), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('sq_foot', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('stories_count', sa.Integer(), nullable=True),
    sa.Column('basement_type', sa.String(length=255), nullable=True),
    sa.Column('addition_type', sa.String(length=255), nullable=True),
    sa.Column('bedroom_count', sa.Integer(), nullable=True),
    sa.Column('full_bath_count', sa.Integer(), nullable=True),
    sa.Column('half_bath_count', sa.Integer(), nullable=True),
    sa.Column('parking_type', sa.String(length=255), nullable=True),
    sa.Column('countertops', sa.String(length=255), nullable=True),
    sa.Column('appliances', sa.String(length=255), nullable=True),
    sa.Column('double_oven_ind', sa.Boolean(), nullable=True),
    sa.Column('walk_in_pantry_ind', sa.Boolean(), nullable=True),
    sa.Column('separate_cooktop_ind', sa.Boolean(), nullable=True),
    sa.Column('built_in_oven_ind', sa.Boolean(), nullable=True),
    sa.Column('built_in_microwave_ind', sa.Boolean(), nullable=True),
    sa.Column('kitchen_flooring', sa.String(length=255), nullable=True),
    sa.Column('main_flooring', sa.String(length=255), nullable=True),
    sa.Column('bathroom_flooring_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_vinyl_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_laminate_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_hardwood_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_travertine_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_saltillo_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_carpet_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_woodplank_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_concrete_ind', sa.Boolean(), nullable=True),
    sa.Column('bathroom_flooring_other_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_vinyl_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_laminate_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_hardwood_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_travertine_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_saltillo_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_carpet_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_woodplank_tile_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_concrete_ind', sa.Boolean(), nullable=True),
    sa.Column('bedroom_flooring_other_ind', sa.Boolean(), nullable=True),
    sa.Column('landscaping', sa.String(length=255), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('hottub', sa.Boolean(), nullable=True),
    sa.Column('gated_community_ind', sa.Boolean(), nullable=True),
    sa.Column('hoa_ind', sa.Boolean(), nullable=True),
    sa.Column('age_restricted_ind', sa.Boolean(), nullable=True),
    sa.Column('solar_panels_ind', sa.Boolean(), nullable=True),
    sa.Column('septic_system_ind', sa.Boolean(), nullable=True),
    sa.Column('well_water_ind', sa.Boolean(), nullable=True),
    sa.Column('poor_location_ind', sa.Boolean(), nullable=True),
    sa.Column('sinkholes_ind', sa.Boolean(), nullable=True),
    sa.Column('foundation_issues', sa.Boolean(), nullable=True),
    sa.Column('additional_info', sa.String(length=1500), nullable=True),
    sa.Column('submitter_type', sa.String(length=255), nullable=True),
    sa.Column('listed_ind', sa.Boolean(), nullable=True),
    sa.Column('submitter_first_name', sa.String(length=255), nullable=True),
    sa.Column('submitter_last_name', sa.String(length=255), nullable=True),
    sa.Column('submitter_phone', sa.String(length=255), nullable=True),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('property')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('address')
    # ### end Alembic commands ###
